### PR TITLE
KAN-15: Share blog articles on Discours with comment section

### PR DESCRIPTION
**Pull request by AnthonyCvn**

### CODE REVIEW

**Comment by AnthonyCvn** [comment]
@atimin I figured out a way to embed comments. Also checkout the forum theme if you like it (then we don't touch it again, because the embed CSS is also defined in the theme).

**Review by atimin — CHANGES_REQUESTED** [review]
I love it! Only  found that it could be a button I think:

image

Like it is here:

image

Another question, could it be possible to export a blog with its tags to the forum?

**Comment by atimin** [comment]
Oh, just found:
image

Did you do it on purpose?

**Comment by AnthonyCvn** [comment]
@atimin after exploring further, it looks like:

- the tags can't be set from
 the embedding; there is potentially a solution to have an automation (but that's a plugging on the pro plan at 200$/m). My proposal is to do it manually for now when we get replies on some post; we can edit the title and add a few relevant tags.
- the topics are unlisted by default (although I unchecked the settings "Imported topics will be unlisted until there is a reply."). Maybe a bug, but at least the topic is automatically listed as soon as it gets a reply:

Screenshot 2024-11-26 at 22 03 54

**Review by atimin — APPROVED** [review]
Okay, then let's merge!

**Pull request merged**
