### PR TITLE
RS-189: Add stripe links to the pricing page

### PR DESCRIPTION
**Pull request by AnthonyCvn**
Changes Introduced:

- Stripe Payment Links: Added direct Stripe payment links for each pricing plan.
- Terms & Conditions Checkbox: Mandatory checkbox for users to agree to the Terms & Conditions before accessing the payment links.

### CODE REVIEW

**Review by atimin — CHANGES_REQUESTED** [review]
It's almost perfect, let's elaborated the free plan:
* remove the check terms and condition checkbox, it is applicable only for commercial plans
* maybe it makes sense to rename the button to "Get Started" or Download and redirect to the download page. I think we should  show that there are no obstacles to get the software.

**Review by AnthonyCvn — COMMENTED** [review]
> It's almost perfect, let's elaborated the free plan:
* remove the check terms and condition checkbox, it is applicable only for commercial plans
* maybe it makes sense to rename the button to "Get Started" or Download and redirect to the download page. I think we should  show that there are no obstacles to get the software. 

Good point, I just made the changes

**Review by atimin — CHANGES_REQUESTED** [review]
Could it possible to make all the plans have the same height? 

image

**Comment by AnthonyCvn** [comment]
Option 1:
option-1

Option 2:
option-2

Option 3:
option-3

Option 4:
option-4

@atimin I know the issue, I tried many layout ;)

I prefer the first option, but I'm okay with option 3 (if you have a good text), or option 4.

**Comment by atimin** [comment]
@atimin  let's do the 3rd then.  We can put a link to the BUSL license at github

**Comment by AnthonyCvn** [comment]
@atimin we have a plan :)

**Review by atimin — APPROVED** [review]
Perfect!

**Pull request merged**
